services:
  db:
    image: postgres:13
    container_name: yellobook
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "client_encoding=UTF8"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis_data:/data


volumes:
  postgres_data:
  redis_data:
