services:
  db:
    image: postgres:13
    container_name: yellobook-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "client_encoding=UTF8"]
    networks:
      - yellobook-network

  redis:
    image: redis:7
    container_name: yellobook-redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - yellobook-network


volumes:
  postgres_data:
  redis_data:

networks:
  yellobook-network:
    driver: bridge
    # 식별을 위해 폴더 이름이 붙는 것을 방지
    name: yellobook-network
