spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: false

cookie:
  expiration: 3600
  domain: localhost
  max-age: 300
  access-name: test_ac
  refresh-name: test_rf

frontend:
  auth-redirect-url: https://yellobook.site/loading
  base-url: https://yellobook.site
  allowance-redirect-url: https://yellobook.site/login/term

backend:
  base-url: https://api.yellobook.site

# 테스트용 더미 secret
jwt:
  access:
    secret: yFys8iTDDSHYm5J66i1jb9o95m81fUidytWfgxn6xBC4DaZ4D2qMoKSD104y0QHe
    expires-in: 7200
  refresh:
    secret: vBDO7fhzECjBsLybYc7GehbTZqJzgyfP4vHvn3NDY2TxcbTSmGnNp5pUjzMmmVuy
    expires-in: 604800
  allowance:
    secret: asdDS3WWEWQSDFSGHJSDSADWCBHMUKU243sfdsfp3ADVCDEdsWEREWFSDasSADAQ
    expires-in: 900

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR