SET FOREIGN_KEY_CHECKS = 0;

-- 테이블의 데이터를 삭제
DELETE FROM inform_mentions;
DELETE FROM inform_comments;
DELETE FROM informs;
DELETE FROM order_comments;
DELETE FROM order_mentions;
DELETE FROM orders;
DELETE FROM products;
DELETE FROM inventories;
DELETE FROM participants;
DELETE FROM teams;
DELETE FROM members;

-- AUTO_INCREMENT 값 초기화
ALTER TABLE inform_mentions AUTO_INCREMENT = 1;
ALTER TABLE inform_comments AUTO_INCREMENT = 1;
ALTER TABLE informs AUTO_INCREMENT = 1;
ALTER TABLE order_comments AUTO_INCREMENT = 1;
ALTER TABLE order_mentions AUTO_INCREMENT = 1;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE products AUTO_INCREMENT = 1;
ALTER TABLE inventories AUTO_INCREMENT = 1;
ALTER TABLE participants AUTO_INCREMENT = 1;
ALTER TABLE teams AUTO_INCREMENT = 1;
ALTER TABLE members AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
