services:
  redis:
    image: redis:7.0.12
    container_name: yellobook-redis
    ports:
      - "6378:6379"
    volumes:
      - ./data:/data
    networks:
      - yellobook-network

networks:
  yellobook-network:
    external: true