services:
  app:
    image: ywoosang/yellobook-server:latest
    container_name: yellobook-server
    ports:
      - "8080:8080"
    networks:
      - yellobook-network
    volumes:
      - /home/ubuntu/pinpoint/agent:/pinpoint
    entrypoint:
      - "java"
      - "-javaagent:/pinpoint/pinpoint-bootstrap-2.5.1.jar"
      - "-Dpinpoint.agentId=yellobook-agent"
      - "-Dpinpoint.applicationName=yellobook-backend"
      - "-Dspring.profiles.active=${PROFILE}"
      - "-Duser.timezone=Asia/Seoul"
      - "yellobook-server.jar"
networks:
  yellobook-network:
    external: true