SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE inform_mentions;
TRUNCATE TABLE inform_comments;
TRUNCATE TABLE informs;
TRUNCATE TABLE order_comments;
TRUNCATE TABLE order_mentions;
TRUNCATE TABLE orders;
TRUNCATE TABLE products;
TRUNCATE TABLE inventories;
TRUNCATE TABLE participants;
TRUNCATE TABLE teams;
TRUNCATE TABLE members;

SET FOREIGN_KEY_CHECKS = 1;