name: Jacoco CI Test

on:
  # CI 는 PR 시에만 동작
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 서브모듈을 포함해서 checkout
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: SonarCloud 패키지 캐시 설정
        uses: actions/cache@v3
        with:
          # 캐시가 저장되는 디렉토리 경로
          path: ~/.sonar/cache
          # 캐시 저장에 사용할 키
          key: ${{ runner.os }}-sonar
          # 캐시가 존재하지 않을 경우 복원 시도
          restore-keys: ${{ runner.os }}-sonar

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle 빌드 후 SonarCloud 정적분석
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew clean build sonar --info

      - name: CodeCoverage 업로드
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
        continue-on-error: false