name: Develop Branch CI

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 checkout
        uses: actions/checkout@v3
        with:
          # 서브모듈을 포함해서 checkout
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: 도커허브 접속을 위해 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 도커 이미지 빌드 후 Docker Hub 에 업로드
        run: |
          docker build -t ywoosang/yellobook-server:latest -f Dockerfile.dev .
          docker push ywoosang/yellobook-server:latest
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 리포지토리 checkout
        uses: actions/checkout@v3

      - name: docker-compose.dev.yml 파일을 EC2 로 복사
        # 공식문서 https://github.com/appleboy/scp-action
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "docker-compose.dev.yml"
          target: "~/yellobook/docker-compose.yml"
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM_KEY }}
          port: 22

      - name: EC2 에서 docker-compose 실행
        # 공식문서 https://github.com/appleboy/ssh-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM_KEY }}
          port: 22
          script: |
            cd ~/yellobook
            docker-compose down
            docker-compose pull
            docker-compose up -d
