name: Test Report

on:
  # CI 는 PR 시에만 동작
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 서브모듈을 포함해서 checkout
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle 빌드
        run: ./gradlew clean build
        continue-on-error: true  # 테스트가 실패하더라도 다음 단계로 넘어감

      - name: Test Report 제작
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./yellobook-domain/build/reports/tests/test/
